services:
  backend:
    build:
      context: backend
      target: builder
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy

  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    #image: mariadb:10-focal
    # If you really want to use MySQL, uncomment the following line
    image: mysql:5.7.44
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 3306:3306
    expose:
      - 3306

  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
#    volumes:
#      - type: bind
#        source: ./proxy/nginx.conf
#        target: /etc/nginx/conf.d/default.conf
#        read_only: true
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/vhost:/vhost:ro
      - ./proxy/ssl:/ssl:ro
      - ./logs:/var/log/nginx                 # 挂载日志目录到宿主机目录
   # depends_on:
   #   - backend

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
